services:
  mysql:
    image: mysql:8.4
    container_name: queen-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: queen
    ports:
      - "3306:3306"
    volumes:
      - queen_mysql_data:/var/lib/mysql
volumes:
  queen_mysql_data: